// The storefront widget catalog shown on the app Widgets page (app/routes/app.widgets.jsx)
// and in the public install guide (app/routes/how-to-install-widgets). Keep one list so
// names, order and images stay identical in both places.

// blockHandle = the theme app extension block's .liquid filename (without extension),
// used to build the "addAppBlockId" deep link into the Theme Editor.
export const WIDGETS = [
  {
    key: "review_wall",
    title: "Review Wall",
    image: "/images/Review%20Wall%202.png",
    description: "A full dedicated page showing all your store reviews in a searchable, filterable grid. Great for SEO — auto-injects AggregateRating schema for Google star snippets.",
    href: "/app/widgets/review-wall",
    blockHandle: "review-wall",
    bg: "linear-gradient(135deg,#fce7f3,#f9a8d4)",
    badge: "NEW",
  },
  {
    key: "homepage_reviews",
    title: "Homepage Reviews",
    description: "Full-page review showcase for your home page — 5 layouts: Summary Carousel, Grid, Masonry, Spotlight, Ticker. Colors and fonts managed from the app.",
    href: "/app/widgets/homepage_reviews",
    blockHandle: "homepage-reviews",
    bg: "linear-gradient(135deg,#fef3c7,#fde68a)",
    badge: "NEW",
  },
  {
    key: "custom_template",
    title: "Custom Template",
    description: "Use your own design from the Customize page — layout, colors, cards and fonts all driven by your active template.",
    href: "/app/customize",
    blockHandle: "custom-template",
    bg: "linear-gradient(135deg,#ede9fe,#c4b5fd)",
    badge: "NEW",
  },
  {
    key: "review_widget",
    title: "Review Widget",
    description: "Collect and display product reviews directly on your product pages.",
    href: "/app/widgets/review_widget",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#dff5e1,#bfe9c6)",
  },
  {
    key: "inline_rating",
    title: "Inline Star Rating",
    description: "A compact ★★★★★ 4.6 out of 5 based on 1,634 reviews badge — embed anywhere via a single div snippet.",
    href: "/app/widgets/inline_rating",
    blockHandle: "inline-rating",
    bg: "linear-gradient(135deg,#fffbe6,#fef08a)",
  },
  {
    key: "star_rating_badge",
    title: "Star Rating Badge",
    description: "Show off your product ratings and review count with a compact badge.",
    href: "/app/widget-settings",
    blockHandle: "star_rating",
    bg: "linear-gradient(135deg,#d9ecff,#bcd9f9)",
  },
  {
    key: "reviews_summary",
    title: "Reviews Summary",
    description: "Heading, star rating breakdown, write-a-review button, trust badges, sort and pagination — all in one widget.",
    href: "/app/widgets/reviews-summary",
    blockHandle: "reviews-summary",
    bg: "linear-gradient(135deg,#ede9fe,#ddd6fe)",
  },
  {
    key: "write_review",
    title: "Write a Review",
    description: "Make it easy for customers to speak up — a clean, on-brand review form.",
    href: "/app/widgets/write-review",
    blockHandle: "review",
    bg: "linear-gradient(135deg,#e8f5d0,#cfe8a8)",
  },
  {
    key: "review_list",
    title: "Review List Design",
    description: "Pick a layout for your review list, style the cards, and set how many reviews show per page.",
    href: "/app/widgets/review-list",
    blockHandle: "review",
    bg: "linear-gradient(135deg,#fde8e8,#f7c2c2)",
  },
  {
    key: "cards_carousel",
    title: "Cards Carousel",
    description: "Bring your best reviews to life in an eye-catching carousel.",
    href: "/app/widgets/cards_carousel",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#ffe9d6,#ffd2ac)",
  },
  {
    key: "testimonial_carousel",
    title: "Testimonial Carousel",
    description: "Showcase your best testimonials beautifully so visitors notice them.",
    href: "/app/widgets/testimonial_carousel",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#e3e0ff,#c7c1ff)",
  },
  {
    key: "videos_carousel",
    title: "Videos Carousel",
    description: "Bring reviews to life with a wall of customer photos and videos.",
    href: "/app/widgets/videos_carousel",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#ffe0ec,#ffc2d6)",
  },
  {
    key: "popup_reviews",
    title: "Pop-up Reviews",
    description: "Perfect timing is everything. Showcase your best reviews exactly when shoppers need that little push.",
    href: "/app/widgets/popup_reviews",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#d6f5f0,#aee8de)",
  },
  {
    key: "ai_reviews_summary",
    title: "AI Reviews Summary",
    description: "Showcase an AI generated summary of your store's reviews to build instant trust.",
    href: "/app/widgets/ai-summary",
    blockHandle: "ai-summary",
    bg: "linear-gradient(135deg,#e0f0ff,#bcdcff)",
  },
  {
    key: "single_review",
    title: "Single Review",
    description: "Show one review at a time with simple next/previous paging — clean and focused.",
    href: "/app/widgets/single_review",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#fef0e6,#fcd9b8)",
  },
  {
    key: "summary_list",
    title: "Summary + List",
    image: "/images/summary-list.png",
    description: "Rating breakdown panel beside a full review list — position the summary left, right, top, or bottom.",
    href: "/app/widgets/summary_list",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#e8fef0,#b8f5ce)",
  },
  {
    key: "classic_list",
    title: "Classic Reviews List",
    description: "Clean paginated list with sort dropdown — the most readable layout for long, detailed reviews.",
    href: "/app/widgets/classic_list",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#e3f4ff,#b8def7)",
  },
  {
    key: "review_snippets",
    title: "Review Snippets",
    description: "Boost conversions by showing your best review snippets, giving shoppers instant social proof.",
    href: "/app/widgets/review_snippets",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#fff3d6,#ffe3a3)",
  },
  {
    key: "questions_answers",
    title: "Questions & Answers",
    image: "/images/questions-answers.png",
    description: "Let shoppers ask questions and get answers right on your product pages.",
    href: "/app/widgets/qa",
    blockHandle: "qa",
    bg: "linear-gradient(135deg,#d6e9ff,#aecdf5)",
  },
  {
    key: "happy_customers",
    title: "Happy Customers widget",
    description: "Bring reviews to life with a wall of happy, smiling customers.",
    href: "/app/widgets/happy_customers",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#dff0e3,#b9dec0)",
  },
  {
    key: "reviews_grid",
    title: "Reviews Grid",
    description: "Display your reviews in a clean, scannable grid layout.",
    href: "/app/widgets/reviews_grid",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#102a43,#1c3f5f)",
    iconColor: "#fff",
  },
  {
    key: "insta_stories",
    title: "Insta Stories",
    description: "Instagram-style photo & video reviews in six designs: Stories tray, Reels feed, Reels Carousel, Social Mix collage, Phone Showcase and Swipe Deck. Switch designs in Widget Design.",
    href: "/app/widgets/insta_stories",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#feda75,#d62976,#4f5bd5)",
    badge: "NEW",
  },
  {
    key: "hero_quote_carousel",
    title: "Hero Quote Carousel",
    description: "Full-bleed crossfading slides with a review's photo as the backdrop and a large centered quote overlay — a magazine-style hero look.",
    href: "/app/widgets/hero_quote_carousel",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#1a1a2e,#6B1A2C)",
    iconColor: "#fff",
    badge: "NEW",
  },
  {
    key: "coverflow_carousel",
    title: "Coverflow Carousel",
    description: "The active review sits centered at full size while neighboring cards peek in at reduced scale on either side — tap a side card to jump to it.",
    href: "/app/widgets/coverflow_carousel",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#e0d4fc,#b8a1f0)",
    badge: "NEW",
  },
  {
    key: "split_media_carousel",
    title: "Split Media Carousel",
    description: "Photo or video on one side, the review text on the other — one review per slide, premium testimonial-section styling.",
    href: "/app/widgets/split_media_carousel",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#d6e9ff,#8fb8f0)",
    badge: "NEW",
  },
  {
    key: "floating_reviews_tab",
    title: "Floating Reviews Tab",
    description: "Access all your reviews through a floating tab at the side of the page.",
    href: "/app/widgets/floating_reviews_tab",
    blockHandle: "reviews-widget",
    bg: "linear-gradient(135deg,#dbe9ff,#aac4f0)",
  },
  {
    key: "trust_medals",
    title: "Trust Medals",
    description: "Display a trust badge with your rating, review count, and a verified ribbon.",
    href: "/app/widgets/trust_medals",
    blockHandle: "trust-medals",
    bg: "linear-gradient(135deg,#e6f4ea,#bfe3cb)",
  },
  {
    key: "verified_counter",
    title: "Verified Reviews Counter",
    description: "Display the number of verified reviews a product has received.",
    href: "/app/widgets/verified_counter",
    blockHandle: "verified-counter",
    bg: "linear-gradient(135deg,#d8f3e0,#a8e0bb)",
  },
  {
    key: "all_reviews_counter",
    title: "All Reviews Counter",
    description: "Show the total number of reviews you've received and their average rating.",
    href: "/app/widgets/all_reviews_counter",
    blockHandle: "all-reviews-counter",
    bg: "linear-gradient(135deg,#fdeacb,#f8d59a)",
  },
  {
    key: "instagram_shopping",
    title: "UCC Instagram Shopping",
    description: "Take your favorite user-generated content from Instagram and pull it into a grid.",
    href: "/app/widgets/instagram-shopping",
    bg: "linear-gradient(135deg,#fce4ec,#f3b8cf)",
  },
  {
    key: "google_reviews",
    title: "Google Reviews",
    description: "Pull your store's own Google rating and reviews onto the storefront — 15 designs, from a minimal badge to a full testimonial wall.",
    href: "/app/widgets/google-reviews",
    blockHandle: "google-reviews",
    bg: "linear-gradient(135deg,#e8f0fe,#c2d9fc)",
    badge: "PRO",
  },
  {
    key: "customer_accounts",
    title: "Customer accounts widgets",
    description: "Let customers write and view reviews, and see rewards directly on the order confirmation page.",
    href: "/app/widgets/customer-accounts",
    bg: "linear-gradient(135deg,#e8e8f0,#c5c5da)",
  },
];
